memory_limit = 128M
max_execution_time = 60
session.use_cookies = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.cookie_secure = 0
session.save_handler = files
session.use_trans_sid = 0
session.name = KASIBUYS
extension=pdo_mysql
extension=mysqli